name: Build Windows Game

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt
      - name: Run PyInstaller
        run: |
          pyinstaller -F game.py
      - name: Build Game Config
        run: |
          python buildconfig.py
      - name: Build Game Cache
        run: |
          python init_data.py
      - name: Copy Game Files
        run: |
          Copy-Item data dist/ -Recurse
          Copy-Item config.ini dist/
          Copy-Item LICENSE dist/
          Copy-Item README.md dist/
          Copy-Item image dist/ -Recurse
          Copy-Item update.log dist/
          Copy-Item package.json dist/
          Copy-Item example dist/ -Recurse
          Rename-Item dist erArk
      - name: Pack Game Files
        run: |
          Compress-Archive -Path erArk\* -DestinationPath erArk.zip
      - name: Run PyInstaller_ArkEditor
        run: |
          pyinstaller -F tools/ArkEditor/main.py
      - name: Copy ArkEditor Files
        run: |
          New-Item -ItemType Directory -Force dist_ArkEditor
          Copy-Item dist/main.exe dist_ArkEditor/ -Force
          Copy-Item tools/ArkEditor/Premise.csv dist_ArkEditor/
          Copy-Item tools/ArkEditor/Status.csv dist_ArkEditor/
          Copy-Item tools/ArkEditor/Effect.csv dist_ArkEditor/
          Copy-Item tools/ArkEditor/Ability.csv dist_ArkEditor/
          Copy-Item tools/ArkEditor/CharacterState.csv dist_ArkEditor/
          Copy-Item tools/ArkEditor/Experience.csv dist_ArkEditor/
          Copy-Item tools/ArkEditor/Juel.csv dist_ArkEditor/
          Copy-Item tools/ArkEditor/Talent.csv dist_ArkEditor/
          Copy-Item example/999_模板人物口上文件.csv dist_ArkEditor/
          Copy-Item example/999_模板人物属性文件.csv dist_ArkEditor/
      - name: Pack ArkEditor Files
        run: |
          Compress-Archive -Path dist_ArkEditor\* -DestinationPath erArkEditor.zip
      - uses: actions/upload-artifact@master
        with:
          name: Windows
          path: erArk.zip
      - name: Read Version
        id: version
        uses: ashley-taylor/read-json-property-action@v1.0
        with:
          path: package.json
          property: version
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{steps.version.outputs.value}}
          release_name: ${{steps.version.outputs.value}}
          body: 除了游戏本体(erArk.zip)，别忘了下载游戏所需的字体包(font.zip)。想要写口上和事件的话，可以下载编辑器(erArkEditor.zip)。
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/erArk.zip
          asset_name: erArk_${{steps.version.outputs.value}}.zip
          asset_content_type: application/zip
      - name: Upload Font Asset
        id: upload-font-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/游戏字体包.zip
          asset_name: font.zip
          asset_content_type: application/zip
      - name: Upload ArkEditor Asset
        id: upload-ArkEditor-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/erArkEditor.zip
          asset_name: erArkEditor.zip
          asset_content_type: application/zip
  