name: Build Windows Game

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Run PyInstaller
        run: |
          pyinstaller -F game.py

      - name: Build Game Config
        run: |
          python buildconfig.py

      - name: Build Game Cache
        run: |
          python init_data.py

      - name: Copy Game Files
        run: |
          Copy-Item data dist/ -Recurse
          Copy-Item config.ini dist/
          Copy-Item LICENSE dist/
          Copy-Item README.md dist/
          Copy-Item image dist/ -Recurse
          Copy-Item update.log dist/
          Copy-Item package.json dist/
          Copy-Item example dist/ -Recurse
          Rename-Item dist erArk

      - name: Pack Game Files
        run: |
          Compress-Archive -Path erArk\* -DestinationPath erArk.zip

      - name: Run PyInstaller_ArkEditor
        run: |
          pyinstaller -F tools/ArkEditor/main.py

      - name: Copy ArkEditor Files
        run: |
          New-Item -ItemType Directory -Force dist_ArkEditor
          New-Item -ItemType Directory -Force dist_ArkEditor/csv
          Copy-Item dist/main.exe dist_ArkEditor/ -Force
          Copy-Item tools/ArkEditor/csv/Premise.csv dist_ArkEditor/csv/
          Copy-Item tools/ArkEditor/csv/PremiseGroup.csv dist_ArkEditor/csv/
          Copy-Item tools/ArkEditor/csv/Status.csv dist_ArkEditor/csv/
          Copy-Item tools/ArkEditor/csv/Effect.csv dist_ArkEditor/csv/
          Copy-Item tools/ArkEditor/csv/Organ.csv dist_ArkEditor/csv/
          Copy-Item data/csv/Ability.csv dist_ArkEditor/csv/
          Copy-Item data/csv/CharacterState.csv dist_ArkEditor/csv/
          Copy-Item data/csv/Experience.csv dist_ArkEditor/csv/
          Copy-Item data/csv/Juel.csv dist_ArkEditor/csv/
          Copy-Item data/csv/Talent.csv dist_ArkEditor/csv/
          Copy-Item data/csv/ClothingType.csv dist_ArkEditor/csv/
          Copy-Item data/csv/Birthplace.csv dist_ArkEditor/csv/
          Copy-Item data/csv/Nation.csv dist_ArkEditor/csv/
          Copy-Item data/csv/Race.csv dist_ArkEditor/csv/
          Copy-Item data/csv/Profession.csv dist_ArkEditor/csv/
          Copy-Item example/999_模板人物口上文件.csv dist_ArkEditor/
          Copy-Item example/999_模板人物属性文件.csv dist_ArkEditor/
          Copy-Item example/模板事件.json dist_ArkEditor/

      - name: Get previous release tag
        id: prev_tag
        run: |
          $prevTag = $(git describe --tags --abbrev=0)
          echo "Previous release tag: $prevTag"
          echo "::set-output name=tag::$prevTag"

      - name: Get commits between tags
        id: commits
        run: |
          $prevTag = ${{ steps.prev_tag.outputs.tag }}
          echo "Previous tag: $prevTag"
          $commits = $(git log $prevTag..HEAD --pretty=format:"%h %s")
          echo "Commits: $commits"
          echo "::set-output name=commits::$commits"

      - name: Output commits for verification
        run: |
          echo "Commits between tags: ${{ steps.commits.outputs.commits }}"

      - name: Pack ArkEditor Files
        run: |
          Compress-Archive -Path dist_ArkEditor\* -DestinationPath erArkEditor.zip
      - uses: actions/upload-artifact@master
        with:
          name: Windows
          path: erArk.zip

      - name: Read Version
        id: version
        uses: ashley-taylor/read-json-property-action@v1.0
        with:
          path: package.json
          property: version

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{steps.version.outputs.value}}
          release_name: ${{steps.version.outputs.value}}
          body: |
            游戏本体 - erArk.zip
            游戏所需的字体包（用于绘制AA地图） - font.zip
            口上事件编辑器（字面意思上的无需写代码即可写口上） -- erArkEditor.zip
            源代码 - Source code
          
            ${{ steps.commits.outputs.commits }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/erArk.zip
          asset_name: erArk_${{steps.version.outputs.value}}.zip
          asset_content_type: application/zip

      - name: Upload Font Asset
        id: upload-font-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/游戏字体包.zip
          asset_name: font.zip
          asset_content_type: application/zip

      - name: Upload ArkEditor Asset
        id: upload-ArkEditor-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/erArkEditor.zip
          asset_name: erArkEditor.zip
          asset_content_type: application/zip
  